### ISSUE TITLE
H1 aligning left

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/adoption#4]
Hi. A H1 on a couple of pages are aligning left but we're not sure why. They are http://www.kent.gov.uk/_adoption-beta/about-us/contact and http://www.kent.gov.uk/_adoption-beta/how-to-adopt/how-to-apply

They're using the same template as other pages which are fine but these ones aren't. Please could you have a look and amend? Thanks.

**Comment by CatherineIles** [comment]
Doh. Fixed Application process and Contact us. The wrong generic paint layout was applied (think it was still a fostering one). @charlottesales

**Comment by charlottesales** [comment]
Ah!

Kind Regards

Charlotte

Charlotte Sales | Digital Services Project Officer | Kent County Council | Internal: 7200 416639 | External: 03000 416639 | www.kent.gov.uk<http://www.kent.gov.uk/> | [Follow Kent_cc on Twitter] @kent_cc<http://www.twitter.com/kent_cc>
