### ISSUE TITLE
Navigation at desktop

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/adoption#6]
Hi. Now the content is in, we can see that the length of some sub navigation is quite long. It means the sub nav is longer than the page width (see screen grabs below). Please could you review and amend?

![image](https://cloud.githubusercontent.com/assets/10434416/7155869/ee77ab0c-e359-11e4-9937-656a22407255.png)

**Comment by CharlesCarnell** [comment]
The resolution to this would involve the same discussion and development as #7, for the time being I'll reassign this to @natmunckton until we've an agreed action and the Squiz work is pending.
