### ISSUE TITLE
Navigation at mobile

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/adoption#7]
Hi. Now the content's in we can see that the sub nav breaks from the design at tablet. See screen grab below. Please could you review and amend? Can we make the hamburger kick in at tablet rather than just at mobile for example?

![image](https://cloud.githubusercontent.com/assets/10434416/7155907/68bec94a-e35a-11e4-8c13-c23f92c55beb.png)

**Comment by CharlesCarnell** [comment]
Updating the tablet navigation to use the same as mobile is something I'm wary of, we feature no breadcrumbs on the site and use the navigation's active state and sub-navigation to present where the user is on the site, and what other relevant content exists.

The page headers are built to support a different header title from the page title in the CMS, can we use a different title for the navigation ( this would be the name of the asset in Squiz ) and use the full title in the header to the page?

Alternatively, we can update the navigation items to use the short names we provide for each asset?

I'm going to reassign this to @natmunckton as design / content.
