### ISSUE TITLE
Homepage free text 2

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/adoption#8]
Hi. Lidor's been able to remove the news and events from the homepage and implement a free text field which is great. Please could you add to this so we can link from a call to action? CUrrently we're only able to link off by adding an a href in the metadata. Probably easier to discuss when you're back... Thanks

**Comment by CharlesCarnell** [comment]
Could you confirm, is it a button to go beneath the free text field to take users off of the homepage, or the ability to link to that section on the homepage from a different page?

If the first, an appropriate button should be designed. This will also require metadata and paint layout updating, which can be done in half an hour.

If the second, we can add an ID to that section on the page which will allow you to link to that specific section, ie dummysite.co.uk#section3
